spring:
  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: false

        routes:
          # --- Customer Service ---
          - id: customer-service
            uri: lb://customer-service
            predicates:
              - Path=/api/v1/customers/**

          # --- Order Service ---
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**

          # --- Payment Service ---
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/payments/**

          # --- Product Service ---
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/products/**, /api/v1/categories/**

        # --- Global CORS Configuration (Crucial for Frontend) ---
        # This allows your React/Angular/Vue app to talk to the Gateway
        cors:
          allowed-origins:
            - "http://localhost:3000" # React default
            - "http://localhost:4200" # Angular default
            - "http://localhost:5173" # Vite/Vue default
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers: "*"
          allow-credentials: true

server:
  port: 8222


      #example for multiple controllers
#      1. PRODUCT DOMAIN (Handles books, authors, cats)
#      - id: product-service
#        uri: lb://product-service
#        predicates:
#          - Path=/api/v1/books/**, /api/v1/authors/**, /api/v1/categories/**