spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ecom-ms

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

      # CORS Configuration for Reactive Gateway
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200,http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

server:
  port: 8222


      #example for multiple controllers
#      1. PRODUCT DOMAIN (Handles books, authors, cats)
#      - id: product-service
#        uri: lb://product-service
#        predicates:
#          - Path=/api/v1/books/**, /api/v1/authors/**, /api/v1/categories/**