spring:
  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27018
      database: customer_db
      authentication-database: admin

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  cache:
    type: redis
    redis:
      ttl-seconds: ${CACHE_TTL_SECONDS:300}

server:
  port: 8090
  servlet:
    context-path: /api/v1
