spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/order_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

application:
  config:
    customer-service-url: http://localhost:8222/api/v1/customers
    product-service-url: http://localhost:8222/api/v1/products
    payment-service-url: http://localhost:8222/api/v1/payments

server:
  port: 8052
  servlet:
    context-path: /api/v1